# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1102, 793)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(870, 720, 201, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 1031, 691))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        
        #0.Load Image 
        self.groupBox_Load_Image = QtWidgets.QGroupBox(self.widget)
        self.groupBox_Load_Image.setObjectName("groupBox_Load_Image")
        self.widget3 = QtWidgets.QWidget(self.groupBox_Load_Image)
        self.widget3.setGeometry(QtCore.QRect(70, 50, 211, 261))
        self.widget3.setObjectName("widget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Load_Folder = QtWidgets.QPushButton(self.widget3)
        self.Load_Folder.setObjectName("Load_Folder")
        self.verticalLayout.addWidget(self.Load_Folder)
        self.Load_Image_L = QtWidgets.QPushButton(self.widget3)
        self.Load_Image_L.setObjectName("Load_Image_L")
        self.verticalLayout.addWidget(self.Load_Image_L)
        self.Load_Image_R = QtWidgets.QPushButton(self.widget3)
        self.Load_Image_R.setObjectName("Load_Image_R")
        self.verticalLayout.addWidget(self.Load_Image_R)
        self.gridLayout.addWidget(self.groupBox_Load_Image, 0, 0, 1, 1)


        # 1.Camera Calibration
        self.groupBox_Calibration = QtWidgets.QGroupBox(self.widget)
        self.groupBox_Calibration.setObjectName("groupBox_Calibration")
        self.widget1 = QtWidgets.QWidget(self.groupBox_Calibration)
        self.widget1.setGeometry(QtCore.QRect(50, 40, 241, 271))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Find_Corner = QtWidgets.QPushButton(self.widget1)
        self.Find_Corner.setObjectName("Find_Corner")
        self.verticalLayout_3.addWidget(self.Find_Corner)
        self.Find_Intrinsic = QtWidgets.QPushButton(self.widget1)
        self.Find_Intrinsic.setObjectName("Find_Intrinsic")
        self.verticalLayout_3.addWidget(self.Find_Intrinsic)
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_7.setObjectName("groupBox_7")
        self.widget2 = QtWidgets.QWidget(self.groupBox_7)
        self.widget2.setGeometry(QtCore.QRect(20, 20, 181, 91))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Find_Extrinsic_Text = QtWidgets.QLineEdit(self.widget2)
        self.Find_Extrinsic_Text.setObjectName("Find_Extrinsic_Text")
        self.verticalLayout_2.addWidget(self.Find_Extrinsic_Text)
        self.Find_Extrinsic = QtWidgets.QPushButton(self.widget2)
        self.Find_Extrinsic.setObjectName("Find_Extrinsic")
        self.verticalLayout_2.addWidget(self.Find_Extrinsic)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.Find_Distortion = QtWidgets.QPushButton(self.widget1)
        self.Find_Distortion.setObjectName("Find_Distortion")
        self.verticalLayout_3.addWidget(self.Find_Distortion)
        self.Show_Undistorted_Result = QtWidgets.QPushButton(self.widget1)
        self.Show_Undistorted_Result.setObjectName("Show_Undistorted_Result")
        self.verticalLayout_3.addWidget(self.Show_Undistorted_Result)
        self.gridLayout.addWidget(self.groupBox_Calibration, 0, 1, 1, 1)

        
        # 2. Augmented Reality
        self.groupBox_Augmented = QtWidgets.QGroupBox(self.widget)
        self.groupBox_Augmented.setObjectName("groupBox_Augmented")
        self.Show_Word_Text = QtWidgets.QLineEdit(self.groupBox_Augmented)
        self.Show_Word_Text.setGeometry(QtCore.QRect(41, 71, 239, 29))
        self.Show_Word_Text.setObjectName("Show_Word_Text")
        self.widget6 = QtWidgets.QWidget(self.groupBox_Augmented)
        self.widget6.setGeometry(QtCore.QRect(40, 130, 251, 171))
        self.widget6.setObjectName("widget6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Show_Word_On_Board = QtWidgets.QPushButton(self.widget6)
        self.Show_Word_On_Board.setObjectName("Show_Word_On_Board")
        self.verticalLayout_4.addWidget(self.Show_Word_On_Board)
        self.Show_Word_Vertically = QtWidgets.QPushButton(self.widget6)
        self.Show_Word_Vertically.setObjectName("Show_Word_Vertically")
        self.verticalLayout_4.addWidget(self.Show_Word_Vertically)
        self.gridLayout.addWidget(self.groupBox_Augmented, 0, 2, 1, 1)


        # 3. Stereo Disparity Map
        self.groupBox_Steror = QtWidgets.QGroupBox(self.widget)
        self.groupBox_Steror.setObjectName("groupBox_Steror")
        self.widget4 = QtWidgets.QWidget(self.groupBox_Steror)
        self.widget4.setGeometry(QtCore.QRect(60, 70, 201, 181))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Stereo_Disparity_Map = QtWidgets.QPushButton(self.widget4)
        self.Stereo_Disparity_Map.setObjectName("Stereo_Disparity_Map")
        self.verticalLayout_7.addWidget(self.Stereo_Disparity_Map)
        self.Check_Disparity_Value = QtWidgets.QPushButton(self.widget4)
        self.Check_Disparity_Value.setObjectName("Check_Disparity_Value")
        self.verticalLayout_7.addWidget(self.Check_Disparity_Value)
        self.gridLayout.addWidget(self.groupBox_Steror, 1, 0, 1, 1)


        # 4. SIFT
        self.groupBox_SIFT = QtWidgets.QGroupBox(self.widget)
        self.groupBox_SIFT.setObjectName("groupBox_SIFT")
        self.widget5 = QtWidgets.QWidget(self.groupBox_SIFT)
        self.widget5.setGeometry(QtCore.QRect(70, 50, 191, 251))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Load_Image1 = QtWidgets.QPushButton(self.widget5)
        self.Load_Image1.setObjectName("Load_Image1")
        self.verticalLayout_5.addWidget(self.Load_Image1)
        self.Load_Image2 = QtWidgets.QPushButton(self.widget5)
        self.Load_Image2.setObjectName("Load_Image2")
        self.verticalLayout_5.addWidget(self.Load_Image2)
        self.Keypoints = QtWidgets.QPushButton(self.widget5)
        self.Keypoints.setObjectName("Keypoints")
        self.verticalLayout_5.addWidget(self.Keypoints)
        self.Matched_Keypoints = QtWidgets.QPushButton(self.widget5)
        self.Matched_Keypoints.setObjectName("Matched_Keypoints")
        self.verticalLayout_5.addWidget(self.Matched_Keypoints)
        self.gridLayout.addWidget(self.groupBox_SIFT, 1, 1, 1, 1)


        # 5. VGG19
        self.groupBox_VGG19 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_VGG19.setObjectName("groupBox_VGG19")
        self.widget4 = QtWidgets.QWidget(self.groupBox_VGG19)
        self.widget4.setGeometry(QtCore.QRect(60, 40, 191, 271))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Load_Image = QtWidgets.QPushButton(self.widget4)
        self.Load_Image.setObjectName("Load_Image")
        self.verticalLayout_6.addWidget(self.Load_Image)
        self.Show_Augmented_Image = QtWidgets.QPushButton(self.widget4)
        self.Show_Augmented_Image.setObjectName("Show_Augmented_Image")
        self.verticalLayout_6.addWidget(self.Show_Augmented_Image)
        self.Show_Model_Structure = QtWidgets.QPushButton(self.widget4)
        self.Show_Model_Structure.setObjectName("Show_Model_Structure")
        self.verticalLayout_6.addWidget(self.Show_Model_Structure)
        self.Show_Accuracy_and_Loss = QtWidgets.QPushButton(self.widget4)
        self.Show_Accuracy_and_Loss.setObjectName("Show_Accuracy_and_Loss")
        self.verticalLayout_6.addWidget(self.Show_Accuracy_and_Loss)
        self.Inference = QtWidgets.QPushButton(self.widget4)
        self.Inference.setObjectName("Inference")
        self.verticalLayout_6.addWidget(self.Inference)
        self.gridLayout.addWidget(self.groupBox_VGG19, 1, 2, 1, 1)

        
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_Calibration.setTitle(_translate("Dialog", "1. Calibration"))
        self.Find_Corner.setText(_translate("Dialog", "Find Corner "))
        self.Find_Intrinsic.setText(_translate("Dialog", "Find Intrinsic"))
        self.groupBox_7.setTitle(_translate("Dialog", "GroupBox"))
        self.Find_Extrinsic.setText(_translate("Dialog", "Find Extrinsic"))
        self.Find_Distortion.setText(_translate("Dialog", "Find Distortion"))
        self.Show_Undistorted_Result.setText(_translate("Dialog", "Show Undistorted Result​"))
        self.groupBox_Load_Image.setTitle(_translate("Dialog", "Load Image"))
        self.Load_Folder.setText(_translate("Dialog", "Load Folder"))
        self.Load_Image_L.setText(_translate("Dialog", "Load Image L"))
        self.Load_Image_R.setText(_translate("Dialog", "Load Image R"))
        self.groupBox_Steror.setTitle(_translate("Dialog", "3. Stereo Disparity Map"))
        self.Stereo_Disparity_Map.setText(_translate("Dialog", "Stereo Disparity Map "))
        self.Check_Disparity_Value.setText(_translate("Dialog", "Check Disparity Value "))
        self.groupBox_VGG19.setTitle(_translate("Dialog", "5. VGG19"))
        self.Load_Image.setText(_translate("Dialog", "Load Image"))
        self.Show_Augmented_Image.setText(_translate("Dialog", "Show Augmented Image"))
        self.Show_Model_Structure.setText(_translate("Dialog", "Show Model Structure"))
        self.Show_Accuracy_and_Loss.setText(_translate("Dialog", "Show Accuracy and Loss"))
        self.Inference.setText(_translate("Dialog", "Inference"))
        self.groupBox_SIFT.setTitle(_translate("Dialog", "4. SIFT"))
        self.Load_Image1.setText(_translate("Dialog", "Load Image1"))
        self.Load_Image2.setText(_translate("Dialog", "Load Image2"))
        self.Keypoints.setText(_translate("Dialog", "Keypoints"))
        self.Matched_Keypoints.setText(_translate("Dialog", "Matched Keypoints"))
        self.groupBox_Augmented.setTitle(_translate("Dialog", "2. Augmented Reality"))
#         self.Show_Word_Text.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Show_Word_On_Board.setText(_translate("Dialog", " Show Words On Board​"))
        self.Show_Word_Vertically.setText(_translate("Dialog", "Show Words Vertically"))

